CREATE TABLE "ClubRevision" (
	"Id"	INTEGER NOT NULL,
	"ClubId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Updated"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("ClubId") REFERENCES "Club"("Id")
)