BEGIN TRANSACTION;
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (1,1,'Arendal CC','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (2,2,'Birkenes IL','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (3,3,'Blindleia CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (4,4,'Bryne CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (5,5,'CK Sør','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (6,6,'Dølemo IL','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (7,7,'Fevik OCC','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (8,8,'Gjerstad IL','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (9,9,'UPC','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (10,10,'Grimstad SK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (11,11,'Kristiansand CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (12,12,'Lund CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (13,13,'Mandal CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (14,14,'MCK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (15,15,'Plussbank Cervelo','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (16,16,'Søgne CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (17,17,'TOSK','2010');
COMMIT;
