BEGIN TRANSACTION;
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (1,1,'Arendal CC','2013');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (2,2,'Birkenes IL','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (3,3,'Blindleia CK','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (4,4,'Bryne CK','2015');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (5,5,'CK Sør','2012');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (6,6,'Dølemo IL','2013');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (7,7,'FOCC','2010');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (8,8,'Gjerstad IL','2012');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (9,9,'Gjerstad IL / UPC','2018');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (10,10,'Grimstad SK','2011');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (11,11,'KCK','2011');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (12,12,'Lund CK','2015');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (13,13,'Mandal CK','2018');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (14,14,'Plussbank Cervelo','2011');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (15,15,'Søgne CK','2019');
INSERT INTO "ClubRevision" ("Id","ClubId","Name","Updated") VALUES (16,16,'TOSK','2012');
COMMIT;
