BEGIN TRANSACTION;
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (1,1,'Alexander','Sterk-Hansen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (2,2,'Anders','Gustav Birkeland','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (3,3,'Anders','Smith','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (4,4,'Andreas','Sivertsen','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (5,5,'Ane','Iversen','2019',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (6,6,'Anette','Heggemsli','2021',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (7,7,'Anette','Sandberg','2020',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (8,8,'Annar','Gaustad','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (9,9,'Arild','Eidesund','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (10,10,'Arild','Voreland','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (11,11,'Arnfinn','Schjølberg','2021',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (12,12,'Atle','Risøy','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (13,13,'Aurora','Nilsen','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (14,14,'Bent Andre','Støyva','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (15,15,'Bent-L','Bakke','2019',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (16,16,'Birgitte','Ravndal','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (17,17,'Bjørg','Gustavsen','2015',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (18,18,'Bjørn','Birkeland','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (19,19,'Bjørn','Nilsen','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (20,20,'Bjørn Notto','Eppeland','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (21,21,'Bjørn Ole','Kolshus','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (22,22,'Bjørn','Østby','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (23,23,'Bjørnar','Schanke','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (24,24,'Brede','Høygilt','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (25,25,'Camilla','Ellefsen','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (26,26,'Christian','Wulff','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (27,27,'Dag Magne','Vedå','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (28,28,'Dag','Svindseth','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (29,29,'Daniel','Hegland','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (30,30,'Eirek','Gullvåg','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (31,31,'Eirik','Sætra-Pedersen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (32,32,'Elias A','Spikseth','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (33,33,'Erlend','Jerstad','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (34,34,'Espen','Bekkelien','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (35,35,'Espen','Nordtveit','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (36,36,'Even','Fløystad','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (37,37,'Fred','Gyldenaas','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (38,38,'Frode','Kristiansen','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (39,39,'Frode Mong','Skjerli','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (40,40,'Geir','Bjørkås','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (41,41,'Geir Egil','Grimstvedt','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (42,42,'Geir','Heggemsli','2020',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (43,43,'Geir Håkon','Opheim','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (44,44,'Geir','Syrstad','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (45,45,'Geir Werner','Hagen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (46,46,'Geirulf','Stoveland','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (47,47,'Gjermund','Steinsland','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (48,48,'Grunde','Axelsen','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (49,49,'Halfdan','Realfsen','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (50,50,'Hans Olav','Røyr','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (51,51,'Harald','Englund','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (52,52,'Heidi L','Thomassen','2016',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (53,53,'Helene','Kvarenes','2013',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (54,54,'Helge','Steinsland','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (55,55,'Håkon Gullaksen','Aas','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (56,56,'Håvard','Lindland','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (57,57,'Inger','Engebretsen','2019',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (58,58,'Jens Kristian','Jensen','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (59,59,'Joakim','Johnsen','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (60,60,'Johannes','Realfsen','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (61,61,'Johnny','Olsen','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (62,62,'Johny','Johannessen','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (63,63,'Jon Henning','Berntzen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (64,64,'Jon','Rislå','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (65,65,'Julie Meyer','Solvang','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (66,66,'Jørgen','Heggemsli','2021',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (67,67,'Jørgen','Heimsæter','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (68,68,'Kenneth','Olsen','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (69,69,'Kim','Forsberg','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (70,70,'Knut T','Ugland','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (71,71,'Kristian Lund','Kristiansen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (72,72,'Kristian','Pedersen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (73,73,'Kurt','Snemyr Jr.','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (74,74,'Kåre','Hørte','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (75,75,'Kåre-Ivar','Ohrvik','2019',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (76,76,'Kåre','Voreland','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (77,77,'Leif Rune','Skaar','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (78,78,'Linn','Rislå','2017',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (79,79,'Magnar','Sivertsen','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (80,80,'Marcel','Paauw','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (81,81,'Margit Juliane','Realfsen','2015',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (82,82,'Marina','Eriksson','2011',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (83,83,'Mario','Juric','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (84,84,'Marius','Trøim','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (85,85,'Mathias','Johannessen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (86,86,'Mathias','Skjold','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (87,87,'May Britt Skeime','Nilsen','2020',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (88,88,'Merethe','Gabrielsen','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (89,89,'Michel','Boekhout','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (90,90,'Morten','Arentz-Grastvedt','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (91,91,'Morten','Berg','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (92,92,'Nicolai','Wæding','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (93,93,'Notto','Høyland','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (94,94,'Olav','Birkeland','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (95,95,'Ole Christian','Myrmel','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (96,96,'Ole Johnny','Lia','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (97,97,'Per Kristian','Jonassen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (98,98,'Per Øyvind','Kristoffersen','2019',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (99,99,'Petter Marki','Erichsen','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (100,100,'Pål Harald','Svendsen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (101,101,'Ragnar T','Holvik','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (102,102,'Renee C','Røyneland','2010',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (103,103,'Richard Uldal','Risbruna','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (104,104,'Robin','Palm','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (105,105,'Roger','Markussen','2010',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (106,106,'Rolf','Grude','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (107,107,'Rolf Sverre','Schanke','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (108,108,'Ronald','Sund','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (109,109,'Runar','Skuggevik','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (110,110,'Rune','Hystad','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (111,111,'Rune','Strøm','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (112,112,'Sigbjørn B','Sivertsen','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (113,113,'Sigrun','Realfsen','2019',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (114,114,'Siren','Wulff','2017',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (115,115,'Skjalg','Grimnes','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (116,116,'Sondre','Thomassen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (117,117,'Steinar','Kvestad','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (118,118,'Steinar Lund','Kristiansen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (119,119,'Steinar','Sandberg','2021',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (120,120,'Stian','Sjølund','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (121,121,'Stine','Borgli','2015',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (122,122,'Ståle','Huse','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (123,123,'Susanne','Egilstad','2014',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (124,124,'Svein Andre','Lia','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (125,125,'Svein','Omdal','2017',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (126,126,'Thomas','Omholt','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (127,127,'Thorstein','Walle','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (128,128,'Tiril','Bjønnes','2013',2);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (129,129,'Tom A','Hartvigsen','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (130,130,'Tom Helge','Pedersen','2013',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (131,131,'Tommy','Hansen','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (132,132,'Tony','Thorvik','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (133,133,'Tor Martin','Kristiansen','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (134,134,'Tord','Skuggevik','2016',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (135,135,'Torleif','Kleppe','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (136,136,'Trond Harald','Dalane','2012',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (137,137,'Trond L','Vabo','2019',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (138,138,'Trond W','Noble','2018',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (139,139,'Trond-Lauritz','Larsen','2015',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (140,140,'Vegar','Strømman','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (141,141,'Åge','Larsen','2014',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (142,142,'Åsmund','Sivertsen','2011',1);
INSERT INTO "PersonRevision" ("Id","PersonId","Firstname","Lastname","Updated","Sex") VALUES (143,143,'Ørjan','Svaland','2018',1);
COMMIT;
